MULTI_AREA_SKILLS = ["knowledge","profession","craft","perform"]

SKILL_KEY_ABILITIES = { ## All skills and their related abilities
    "appraise"          :   "intelligence",
    "balance"           :   "dexterity",
    "bluff"             :   "charisma",
    "climb"             :   "strength",
    "concentration"     :   "constitution",
    "craft"             :   "intelligence",
    "decipher_script"   :   "intelligence",
    "diplomacy"         :   "charisma",
    "disable_device"    :   "intelligence",
    "disguise"          :   "charisma",
    "escape_artist"     :   "dexterity",
    "forgery"           :   "intelligence",
    "gather_information":   "charisma",
    "handle_animal"     :   "charisma",
    "heal"              :   "wisdom",
    "hide"              :   "dexterity",
    "intimidate"        :   "charisma",
    "jump"              :   "strength",
    "knowledge"         :   "intelligence",
    "listen"            :   "wisdom",
    "move_silently"     :   "dexterity",
    "open_lock"         :   "dexterity",
    "perform"           :   "charisma",
    "profession"        :   "wisdom",
    "ride"              :   "dexterity",
    "search"            :   "intelligence",
    "sense_motive"      :   "wisdom",
    "sleight_of_hand"   :   "dexterity",
    "spellcraft"        :   "intelligence",
    "spot"              :   "wisdom",
    "survival"          :   "wisdom",
    "swim"              :   "strength",
    "tumble"            :   "dexterity",
    "use_magic_device"  :   "charisma",
    "use_rope"          :   "dexterity"
    }

SKILL_USABLE_UNTRAINED = { ## all skills; are they usable untrained or not?
    ## True if usable untrained. False if not.
    "appraise"          :   True,
    "balance"           :   True,
    "bluff"             :   True,
    "climb"             :   True,
    "concentration"     :   True,
    "craft"             :   True,
    "decipher_script"   :   False,
    "diplomacy"         :   True,
    "disable_device"    :   False,
    "disguise"          :   True,
    "escape_artist"     :   True,
    "forgery"           :   True,
    "gather_information":   True,
    "handle_animal"     :   False,
    "heal"              :   True,
    "hide"              :   True,
    "intimidate"        :   True,
    "jump"              :   True,
    "knowledge"         :   False,
    "listen"            :   True,
    "move_silently"     :   True,
    "open_lock"         :   False,
    "perform"           :   False,
    "profession"        :   False,
    "ride"              :   True,
    "search"            :   True,
    "sense_motive"      :   True,
    "sleight_of_hand"   :   False,
    "spellcraft"        :   False,
    "spot"              :   True,
    "survival"          :   True,
    "swim"              :   True,
    "tumble"            :   False,
    "use_magic_device"  :   True,
    "use_rope"          :   True
    }