class Personality:
    """Encapsulates all character personality traits with detailed descriptions."""
    TRAITS = [
        ("Honest", "Truthful and sincere in words and actions, never shirking responsibility for mistakes."),
        ("Kind", "Showing genuine concern and compassion for others, offering help without expectation."),
        ("Respectful", "Treating everyone with dignity and consideration, regardless of status."),
        ("Loyal", "Faithful and steadfast in relationships and commitments, standing by allies through thick and thin."),
        ("Reliable", "Dependable and trustworthy, following through on promises no matter the obstacles."),
        ("Courageous", "Brave and willing to face the most daunting challenges with unwavering resolve."),
        ("Optimistic", "Maintaining a positive outlook on life and the future, even when things look bleak."),
        ("Empathic", "Deeply understanding and sharing the feelings of others, offering comfort when needed."),
        ("Creative", "Inventive and original, constantly generating new ideas to solve problems."),
        ("Intelligent", "Possessing sharp insight and knowledge, able to grasp complex concepts quickly."),
        ("Independent", "Able to function and make confident decisions without relying on others."),
        ("Driven", "Fueled by a strong desire to achieve goals, pushing past limits to succeed."),
        ("Determined", "Holding fast to a chosen path or purpose, refusing to waver in adversity."),
        ("Persistent", "Continuing with effort despite difficulties, never giving up on challenges."),
        ("Organized", "Maintaining order through planning and structure, managing time and tasks effectively."),
        ("Adaptable", "Quickly adjusting to changing circumstances and thriving in new environments."),
        ("Communicative", "Expressing thoughts and feelings clearly and listening to others attentively."),
        ("Helpful", "Always willing to assist those in need, putting others’ well-being first."),
        ("Generous", "Willing to give time, resources, and support to help others flourish."),
        ("Considerate", "Showing thoughtfulness and concern for others’ feelings and needs."),
        ("Patient", "Able to endure delays and setbacks with a calm and composed attitude."),
        ("Thoughtful", "Reflective and insightful, carefully considering actions before taking them."),
        ("Wise", "Offering sound judgment based on experience and practical knowledge."),
        ("Humorous", "Bringing joy and laughter to others with a lighthearted spirit."),
        ("Calm", "Remaining composed and even-tempered under pressure or stress."),
        ("Confident", "Having a strong belief in one’s abilities, facing challenges with assurance."),
        ("Open-minded", "Willing to consider new ideas and perspectives without prejudice."),
        ("Forgiving", "Able to let go of anger and resentment, offering mercy where it’s due."),
        ("Resilient", "Recovering quickly from setbacks, growing stronger through adversity."),
        ("Positive", "Maintaining an upbeat and hopeful attitude, inspiring others around them.")
    ]